# settings.py (Local Development Copy)
# This needs to be synced up as close to settings_env_specific/dev.py as possible
SERVERSIDE_APP_VERSION_STRING = "2.0.1.2020MMDD.localdev" 
ENV_STRING = "localdev"


# #################################################################
# # Imports
# #################################################################

import os

import mimetypes
mimetypes.add_type("text/css", ".css", True)


# #################################################################
# # Other Application Settings
# #################################################################
UNAMBIGUOUS_ALPHA_NUMERIC_CHARS = '23456789abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'




"""


Django settings for climateserv_2_0_serverside project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

#import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#print("BASE_DIR: " + str(BASE_DIR))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^x!qf^2q!v@ff0--p6j=)ykfvr%4e-p&c+zr3@i3ft8=3i#*to'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False

ALLOWED_HOSTS = []      # ['climateserv2-beta-server.servirglobal.net', '10.5.5.68', '216.218.226.161', 'climateserv.servirglobal.net']     # ['*']
#ALLOWED_HOSTS = ['climateserv.servirglobal.net', '216.218.226.161', '10.5.5.68']  # ['*']



# https://stackoverflow.com/questions/43357687/django-python-rest-framework-no-access-control-allow-origin-header-is-present
CORS_ORIGIN_WHITELIST = [
    #'http://google.com',
    #'http://hostname.example.com',
    #'http://127.0.0.1:9000',
    'http://localhost:3000',  # React Admin App
    'http://climateserv.servirglobal.net',
    'http://216.218.226.161',
    'https://climateserv.servirglobal.net',
    'https://climateserv2-beta-admin.servirglobal.net'
]


# Application definition
INSTALLED_APPS = [
    # Add any new Modules here
    
    'api_v2',
    'common_utils',

    # https://stackoverflow.com/questions/43357687/django-python-rest-framework-no-access-control-allow-origin-header-is-present
    'corsheaders',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [

    # https://stackoverflow.com/questions/43357687/django-python-rest-framework-no-access-control-allow-origin-header-is-present
    'corsheaders.middleware.CorsMiddleware',
    #'django.middleware.common.CommonMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'climateserv_2_0_serverside.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'climateserv_2_0_serverside.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db/db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
# Production Server
#STATIC_ROOT='/cserv2/django_app/ClimateSERV-2.0-StaticFiles'

#STATIC_ROOT= os.path.join(BASE_DIR,'static/')
#STATIC_ROOT = '/cserv2/django_app/static/'





# DEPRECATING
# These custom settings have all been moved to the Database.
#
#
# # Custom Settings
#
# # API LOGGING SETTINGS
# API_LOGGING_ENDPOINT_IGNORE_LIST = [
#     #'/api_v2/get_server_versions/',
#     '/api_v2/admin_get_db_item/',
#     '/api_v2/admin_get_api_logs/',
#     '/api_v2/admin_get_etl_logs/',
#     '/api_v2/admin_get_dashboard_data/',
# ]
#
#
# # LOCAL PATH Settings
# #
# # # The Temp Directory on the server's local filesystem where files are downloaded, extracted and transformed
# PATH__TEMP_WORKING_DIR__EMODIS__EA    = '/Volumes/TestData/Data/SERVIR/ClimateSERV_2_0/data/temp_etl_data/emodis/eastafrica/'
# PATH__TEMP_WORKING_DIR__EMODIS__WA    = '/Volumes/TestData/Data/SERVIR/ClimateSERV_2_0/data/temp_etl_data/emodis/westafrica/'
# PATH__TEMP_WORKING_DIR__EMODIS__SA    = '/Volumes/TestData/Data/SERVIR/ClimateSERV_2_0/data/temp_etl_data/emodis/southernafrica/'
# PATH__TEMP_WORKING_DIR__EMODIS__CTA   = '/Volumes/TestData/Data/SERVIR/ClimateSERV_2_0/data/temp_etl_data/emodis/centralasia/'
# #
# # # The Directory on the server's local filesystem where THREDDS is monitoring for NC4 files - This is the destination directory where the load step places the final granule NC4 files.
# PATH__THREDDS_MONITORING_DIR__EMODIS__EA  = '/Volumes/TestData/Data/SERVIR/ClimateSERV_2_0/data/THREDDS/thredds/catalog/climateserv/emodis-ndvi/eastafrica/250m/10dy/'
# PATH__THREDDS_MONITORING_DIR__EMODIS__WA  = '/Volumes/TestData/Data/SERVIR/ClimateSERV_2_0/data/THREDDS/thredds/catalog/climateserv/emodis-ndvi/westafrica/250m/10dy/'
# PATH__THREDDS_MONITORING_DIR__EMODIS__SA  = '/Volumes/TestData/Data/SERVIR/ClimateSERV_2_0/data/THREDDS/thredds/catalog/climateserv/emodis-ndvi/southernafrica/250m/10dy/'
# PATH__THREDDS_MONITORING_DIR__EMODIS__CTA = '/Volumes/TestData/Data/SERVIR/ClimateSERV_2_0/data/THREDDS/thredds/catalog/climateserv/emodis-ndvi/centralasia/250m/10dy/'
#
#
# # DEFAULT PATH SETTINGS
# #
# # Default Path Settings - This is the default/fall back location for where temp files are processed and where THREDDS files are placed if there are any issues in the logic for selecting the correct paths
# PATH__TEMP_WORKING_DIR__DEFAULT           = '/Volumes/TestData/Data/SERVIR/ClimateSERV_2_0/data/temp_etl_data/UNKNOWN/'
# PATH__THREDDS_MONITORING_DIR__DEFAULT     = '/Volumes/TestData/Data/SERVIR/ClimateSERV_2_0/data/THREDDS/thredds/catalog/climateserv/UNKNOWN/'
#
#
#
# # REMOTE PATH SETTINGS
# #
# REMOTE_PATH__ROOT_HTTP__EMODIS__EA      = 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/fews/web/africa/east/dekadal/emodis/ndvi_c6/temporallysmoothedndvi/downloads/dekadal/'      # East Africa
# REMOTE_PATH__ROOT_HTTP__EMODIS__WA      = 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/fews/web/africa/west/dekadal/emodis/ndvi_c6/temporallysmoothedndvi/downloads/dekadal/'      # West Africa
# REMOTE_PATH__ROOT_HTTP__EMODIS__SA      = 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/fews/web/africa/southern/dekadal/emodis/ndvi_c6/temporallysmoothedndvi/downloads/dekadal/'  # Southern Africa
# REMOTE_PATH__ROOT_HTTP__EMODIS__CTA     = 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/fews/web/asia/centralasia/dekadal/emodis/ndvi_c6/temporallysmoothedndvi/downloads/dekadal/' # Central Asia
# #
# # Default Remote Path
# REMOTE_PATH__ROOT_HTTP__DEFAULT         = 'localhost://UNKNOWN_URL'
#
#
# # ETL Logs - Activity Types
# ETL_LOG_ACTIVITY_EVENT_TYPE__DEFAULT                    = "Default ETL Activity Event Type"
# ETL_LOG_ACTIVITY_EVENT_TYPE__UNKNOWN                    = "Unknown ETL Activity Event Type"
# ETL_LOG_ACTIVITY_EVENT_TYPE__PIPELINE_STARTED           = "ETL Pipeline Run Started"
# ETL_LOG_ACTIVITY_EVENT_TYPE__PIPELINE_DIRECTORY_CREATED = "ETL Pipeline Created a new directory."
# ETL_LOG_ACTIVITY_EVENT_TYPE__PIPELINE_STEP_COMPLETED    = "ETL Pipeline Completed Step"
# ETL_LOG_ACTIVITY_EVENT_TYPE__PIPELINE_ENDED             = "ETL Pipeline Run Ended"
# ETL_LOG_ACTIVITY_EVENT_TYPE__ERROR_LEVEL_ERROR          = "ETL Error"
# ETL_LOG_ACTIVITY_EVENT_TYPE__ERROR_LEVEL_WARNING        = "ETL Warning"
# ETL_LOG_ACTIVITY_EVENT_TYPE__TEMP_WORKING_DIR_BLANK     = "Temp ETL Working Directory was blank"
# ETL_LOG_ACTIVITY_EVENT_TYPE__TEMP_WORKING_DIR_REMOVED   = "Temp ETL Working Directory was removed"
# ETL_LOG_ACTIVITY_EVENT_TYPE__DOWNLOAD_PROGRESS          = "ETL Pipeline Download Progress"
#
# #
# # # Step Specific Pipeline Event Tracking - Standardized, human readable names used in the descriptions of event tracking.
# # # The Standardization makes it easier for aggregating the Events into groups.
# ETL_PIPELINE_STEP__PRE_ETL_CUSTOM  = "ETL Pipeline Step 'Pre ETL Custom Processing'"
# ETL_PIPELINE_STEP__DOWNLOAD        = "ETL Pipeline Step 'Download'"
# ETL_PIPELINE_STEP__EXTRACT         = "ETL Pipeline Step 'Extract'"
# ETL_PIPELINE_STEP__TRANSFORM       = "ETL Pipeline Step 'Transform'"
# ETL_PIPELINE_STEP__LOAD            = "ETL Pipeline Step 'Load'"
# ETL_PIPELINE_STEP__POST_ETL_CUSTOM = "ETL Pipeline Step 'Post ETL Custom Processing'"
# ETL_PIPELINE_STEP__CLEAN_UP        = "ETL Pipeline Step 'Clean up'"
# #
# #
# # ETL Dataset SubTypes
# ETL_DATASET_SUBTYPE__CHIRP          = "chrip"
# ETL_DATASET_SUBTYPE__CHIRPS         = "chrips"
# ETL_DATASET_SUBTYPE__CHIRPS_GEFS    = "chrips_gefs"
# ETL_DATASET_SUBTYPE__EMODIS         = "emodis"
# ETL_DATASET_SUBTYPE__ESI_4WEEK      = "esi_4week"
# ETL_DATASET_SUBTYPE__ESI_12WEEK     = "esi_12week"
# ETL_DATASET_SUBTYPE__IMERG_EARLY    = "imerg_early"
# ETL_DATASET_SUBTYPE__IMERG_LATE     = "imerg_late"
#
# GRANULE_PIPELINE_STATE__ATTEMPTING  = "ATTEMPTING"
# GRANULE_PIPELINE_STATE__ATTEMPTED   = "ATTEMPTED"
# GRANULE_PIPELINE_STATE__SUCCESS     = "SUCCESS"
# GRANULE_PIPELINE_STATE__FAILED      = "FAILED"




