# Generated by Django 2.2.2 on 2020-06-21 20:25

import common_utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=common_utils.utils.get_Random_String_UniqueID_20Chars, editable=False, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('created_by', models.CharField(default='Table_Default_Process', help_text='Who or What Process created this record? 90 chars max', max_length=90, verbose_name='Created By User or Process Name or ID')),
                ('additional_json', models.TextField(default='{}', help_text="Extra data field.  Please don't touch this!  Messing with this will likely result in broken content elsewhere in the system.", verbose_name='JSON Data')),
                ('is_test_object', models.BooleanField(default=False, help_text='Is this Instance meant to be used ONLY for internal platform testing? (Used only for easy cleanup - DO NOT DEPEND ON FOR VALIDATION)')),
                ('auth_id', models.CharField(default='UNKNOWN_AUTH_ID', editable=False, max_length=40)),
                ('is_admin', models.BooleanField(default=False, help_text='Is this user an Admin?')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Does this user have permissions to manage Users?')),
                ('can_manage_etl_logs', models.BooleanField(default=False, help_text='Does this user have permissions to manage ETL Logs?')),
                ('can_manage_api_logs', models.BooleanField(default=False, help_text='Does this user have permissions to manage API Logs?')),
                ('can_manage_server_logs', models.BooleanField(default=False, help_text='Does this user have permissions to manage Server Logs?')),
            ],
        ),
    ]
