# Generated by Django 3.0.7 on 2020-07-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0006_available_granule'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_granule',
            name='granule_name',
            field=models.CharField(default='Unknown_Granule_Name', help_text="Most of the time, this may be a filename.  Sometimes it is not.  It should be a name that is unique to the combination of dataset and temporal data value.  This row should be useful in tracking down the specific granule's file/source info.", max_length=250, verbose_name='Granule Name'),
        ),
    ]
