# Generated by Django 3.0.7 on 2020-08-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0009_api_log_server_result_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Setting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('setting_name', models.CharField(default='UNKNOWN_SETTING', help_text='What is the name of this setting.  These are meant to be unique but not constrained by the database.  If there are any settings with the exact same name, please delete the duplicates.', max_length=250, verbose_name='Setting Name')),
                ('setting_value', models.TextField(default='{}', help_text='Setting Value.  Can be a string, or JSON Object, etc.  If this value is just a string or number only, remove the {} default.', verbose_name='Setting Value')),
                ('setting_data_type', models.TextField(default='STRING', help_text="Setting Datatype.  This is important.  Choices are: 'STRING', 'LIST', 'JSON'.  If the datatype is not recognized, then STRING is used.  Note: JSON types are loaded with json.loads(<value>).  Note: LIST types are read as comma separated strings.  Something like '1,2,3' would get converted into ['1','2','3'] to be used in the code.  List Items have to be strings, not numbers, and not complex objects.  List Item Type conversion and validation happens at the code where it is needed.", verbose_name='Setting Data Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
    ]
