# Generated by Django 3.0.7 on 2020-08-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0010_config_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_setting',
            name='setting_data_type',
            field=models.CharField(default='STRING', help_text="Setting Datatype.  This is important.  Choices are: 'STRING', 'LIST', 'JSON'.  If the datatype is not recognized, then STRING is used.  Note: JSON types are loaded with json.loads(<value>).  Note: LIST types are read as comma separated strings.  Something like '1,2,3' would get converted into ['1','2','3'] to be used in the code.  List Items have to be strings, not numbers, and not complex objects.  List Item Type conversion and validation happens at the code where it is needed.", max_length=250, verbose_name='Setting Data Type'),
        ),
    ]
