# Generated by Django 3.0.7 on 2020-12-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0012_task_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl_dataset',
            name='dataset_base_directory_path',
            field=models.CharField(default='UNSET', help_text='This is a field that tells the job processing code where to look to find ALL of the NetCDF files (NC4 files) for this dataset.  In many cases (at this time all cases) this is the same as the setting for the THREDDS output directory. This is an absolute path which means the directory path should begin with /.  The code that uses this also expects a / at the end of the directory name.', max_length=255, verbose_name='Base Directory Path'),
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='dataset_legacy_datatype',
            field=models.CharField(default='0', help_text="The 'datatype' number from ClimateSERV 1.0.  This is mapped in support of Legacy API Requests", max_length=5, verbose_name='Legacy datatype'),
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='dataset_nc4_variable_name',
            field=models.CharField(default='ndvi', help_text='To select data from an NC4 file requires a variable name.  This is the field where a variable name must be set for the selection from NC4 file to work properly.', max_length=40, verbose_name='Variable Name inside NC4 File'),
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='is_lat_order_reversed',
            field=models.BooleanField(default=False, help_text='Some datasets have their lat order reversed.  The downstream affect of this has to do with NC4 data selection.  If this flag is set to True then we use, latitude=slice(max_Lat, min_Lat), if it is set to false, then the selection uses latitude=slice(min_Lat, max_Lat) - Note, at the time of this writing, NDVI types should be set to False'),
        ),
    ]
