# Generated by Django 3.0.7 on 2020-12-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0013_auto_20201217_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_log',
            name='ip_address',
            field=models.CharField(default='UNKNOWN_IP', help_text='What was the IP address of the computer that requested this Task?', max_length=90, verbose_name='What was the IP Address'),
        ),
        migrations.AddField(
            model_name='task_log',
            name='is_errored',
            field=models.BooleanField(default=False, help_text='When this task was processed, were there any errors?'),
        ),
        migrations.AddField(
            model_name='task_log',
            name='job_progress',
            field=models.IntegerField(default=0, help_text='Job Process Progress.  Integer from 0 to 100', verbose_name='Job Progress'),
        ),
        migrations.AddField(
            model_name='task_log',
            name='job_status',
            field=models.CharField(default='Default', help_text="What is the current status of this job.  Current Recognized Enum choices are: 'Waiting_To_Start', 'In_Progress', and 'Processing_Complete' ", max_length=30, verbose_name='Job Status'),
        ),
        migrations.AddField(
            model_name='task_log',
            name='job_uuid',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=40),
        ),
        migrations.AlterField(
            model_name='etl_dataset',
            name='dataset_legacy_datatype',
            field=models.CharField(default='9999', help_text="The 'datatype' number from ClimateSERV 1.0.  This is mapped in support of Legacy API Requests", max_length=5, verbose_name='Legacy datatype'),
        ),
    ]
