# Generated by Django 3.0.7 on 2020-12-23 16:16

import common_utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0014_auto_20201218_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProcess',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=common_utils.utils.get_Random_String_UniqueID_20Chars, editable=False, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('created_by', models.CharField(default='Table_Default_Process', help_text='Who or What Process created this record? 90 chars max', max_length=90, verbose_name='Created By User or Process Name or ID')),
                ('additional_json', models.TextField(default='{}', help_text="Extra data field.  Please don't touch this!  Messing with this will likely result in broken content elsewhere in the system.", verbose_name='JSON Data')),
                ('is_test_object', models.BooleanField(default=False, help_text='Is this Instance meant to be used ONLY for internal platform testing? (Used only for easy cleanup - DO NOT DEPEND ON FOR VALIDATION)')),
                ('is_worker_processing_a_job', models.BooleanField(default=False, help_text='Is this Instance currently processing a job?  When a worker starts processing a job, this should be set to True, when a worker finishes processing a job, this should be set to False')),
                ('should_worker_be_stopped', models.BooleanField(default=False, help_text='This allows us to disable a worker from the database level.  When we disable a worker from the database level, this gets set to True, when a worker starts / initializes, this should be set to False')),
                ('current_run_idle_check_counter', models.IntegerField(default=0, help_text="How many times has this worker done it's idle checkpoint since the last time it has been turned on?  When a worker is first started/initialized, this gets reset to 0.  Each time a worker checks for a job, this value gets incremented.", verbose_name='Current Run Idle Check Counter')),
            ],
        ),
    ]
